# Generated by Django 3.0.4 on 2020-03-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='title',
            new_name='raw_text',
        ),
    ]
