# Generated by Django 3.0.4 on 2020-03-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag_app', '0002_auto_20200327_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='raw_text',
            new_name='input_text',
        ),
    ]
