# Generated by Django 3.0.4 on 2020-03-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag_app', '0004_hashtag_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
