# Generated by Django 3.0.4 on 2020-03-28 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag_app', '0005_auto_20200328_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='uploaded_file',
            new_name='image',
        ),
    ]
