# Generated by Django 3.0.4 on 2020-03-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag_app', '0006_auto_20200328_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='thumb/')),
            ],
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='image',
        ),
    ]
