# Generated by Django 3.0.4 on 2020-03-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag_app', '0007_auto_20200328_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='thumb/'),
        ),
    ]
